### ISSUE TITLE
Renaming our functions

### ISSUE THREAD

**Issue by SamanodyJr** [Khoulykid/DD1-Project-1#10]
Hey!
I was thinking we should rename our functions so they would be more meaningful to anyone reading our project. What do you think? @Khoulykid @nouryasser1

**Comment by Khoulykid** [comment]
Sure. I think I'll also divide my code into further functions and rename the function in it for people to navigate through it more easily.

**Comment by Khoulykid** [comment]
I have renamed all functions including when we call them in the main.
