### ISSUE TITLE
to run the Forth Function

### ISSUE THREAD

**Issue by SamanodyJr** [Khoulykid/DD1-Project-1#4]
@Khoulykid 
I need from your other functions the table as map of char and vector of int, the prime implicants in vector of string, and a vector of vector int that represents minterms covered by each prime implicant in the vector of string. 

Thank you ! <3

**Comment by Khoulykid** [comment]
@SamanodyJr 
I finished it yesterday Midnight. I had a set of strings that contained the PI's but I changed it to a vector of string for your benefit. It is called "pis" and I finally made a 2D vector of int called "minterms" that contains the minterms covered by each PI. The first index represents the index of the PI and the 2nd index represents the "minterm" covered by that PI. E.G minterm[0][3] will show the 4th minterm covered by the first PI given (which is Pi[0[).

You're very welcome!
