### ISSUE TITLE
bug found (Missing PIs function 3)

### ISSUE THREAD

**Issue by SamanodyJr** [Khoulykid/DD1-Project-1#7]
Hey! @Khoulykid I was testing the code using this : a'b'cd'ef'+a'bc'd'ef'+ab'cd'e'f'+abc'd'e'f'+a'bcd'ef'+ab'cd'e'f+ab'cd'ef'+abc'd'e'f+abc'd'ef'+abc'de'f'+abcd'e'f'+abc'de'f+abcd'e'f+abcde'f'+abcde'f 
which is one of the assignment questions and I ran into a bug one of the prime implicants does not show and it is 1-1001 the one covering 41,57. This causes further errors please check it out and lmk if you found out what is wrong. 

GOODLUCK 🍀

**Comment by Khoulykid** [comment]
I'll look into it right now.

**Comment by Khoulykid** [comment]
I just reviewed the code and rechecked. It gives me the correct solution. What is your source for the answer?

**Comment by SamanodyJr** [comment]
On blackboard the HW solution. If what you got is correct ,then it means our code is working fine. Should we check with the TA?

**Comment by Khoulykid** [comment]
I just checked the HW solution. Apparently he wrote an implicant that covers 41,57 and another implicant that covers 41,57, 40,51. So apparently he wrote an extra implicant. I think we should report this to him.

**Comment by Khoulykid** [comment]
I think we can close this issue as it is now. If anyone finds an error with the code anytime please feel free to issue it!
@SamanodyJr @nouryasser1
